### ISSUE TITLE
AssertionErro

### ISSUE THREAD

**Issue by mineechor** [SkyLined/BugId#113]
BugId.cmd -v %WinDir%\system32\rundll32.exe -- advapi32 CloseThreadWaitChainSession
Traceback (most recent call last):
  File "D:\2022\final\BugId.release.2022-12-08.09.57\BugId.py", line 1294, in <module>
    fSaveInternalExceptionReportAndExit(oException, oTraceBack);
  File "D:\2022\final\BugId.release.2022-12-08.09.57\BugId.py", line 202, in fSaveInternalExceptionReportAndExit
    fOutputExceptionInformation(oException, oTraceBack);
  File "D:\2022\final\BugId.release.2022-12-08.09.57\fOutputExceptionInformation.py", line 55, in fOutputExceptionInformation
    fOutputVersionInformation(
  File "D:\2022\final\BugId.release.2022-12-08.09.57\fOutputVersionInformation.py", line 72, in fOutputVersionInformation
    aoProductDetails = mProductDetails.faoGetProductDetailsForAllLoadedModules();
  File "D:\2022\final\BugId.release.2022-12-08.09.57\modules\mProductDetails\faoGetProductDetailsForAllLoadedModules.py", line 6, in faoGetProductDetailsForAllLoadedModules
    o0ProductDetails = cProductDetails.fo0GetForModule(mLoadedModule);
  File "D:\2022\final\BugId.release.2022-12-08.09.57\modules\mProductDetails\cProductDetails.py", line 31, in fo0GetForModule
    assert mProductModule.__file__ is not None, \
AssertionError: __file__ is None for <module 'mpl_toolkits' (namespace)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\2022\final\BugId.release.2022-12-08.09.57\BugId.py", line 1297, in <module>
    m0DebugOutput.fTerminateWithException(
TypeError: fTerminateWithException() got an unexpected keyword argument 'bPauseBeforeExit'

**Comment by SkyLined** [comment]
Handle non-internal, non-product modules better:
https://github.com/SkyLined/mProductDetails/commit/d2b268d2f86422cb0a6b32284adcf643366d51ab

**Comment by SkyLined** [comment]
Properly implement `bPauseBeforeExit`
https://github.com/SkyLined/mDebugOutput/commit/833cf3baf75cf2b26ca51b48c61d9e3010811a3c
