### ISSUE TITLE
access denied -> python hanging forever, report never written

### ISSUE THREAD

**Issue by kokanin** [SkyLined/BugId#18]
foxit reader (well anything really), 
```
 * T+19.1 Exception code 0xC0000005 (Access violation) was detected and is being analyzed...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\BugId-master\modules\cBugId\cCdbWrapper.py", line 213, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "C:\BugId-master\modules\cBugId\cCdbWrapper.py", line 207, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\BugId-master\modules\cBugId\cCdbWrapper_fCdbCleanupThread.py", line 1
6, in cCdbWrapper_fCdbCleanupThread
    oCdbWrapper.oCdbProcess.terminate();
  File "C:\Python27\lib\subprocess.py", line 1016, in terminate
    _subprocess.TerminateProcess(self._handle, 1)
WindowsError: [Error 5] Access is denied
```

normal win7x64, no special setup

**Comment by SkyLined** [comment]
Thanks! I believe the issue is that I cannot call "terminate" on a process that is already terminated: this may throw the exception you are seeing. I've not wrapped the call in a try... except block to prevent this.

https://github.com/SkyLined/cBugId/commit/3aeb97a9b6f9e8f748290db4a1f9250e44a97ec9

**Comment by kokanin** [comment]
that fixed the issue, thanks!
