### ISSUE TITLE
NameError("global name 'oBugId' is not defined",)

### ISSUE THREAD

**Issue by dmitrikaslov** [SkyLined/BugId#23]
Hi

Here is another bug in BugID when running it with 'BugID.bSaveDump=true'

```
T+94.9 The application was resumed successfully and is running...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper.py", line 21
4, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper.py", line 20
8, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper_fCdbStdInOut
Thread.py", line 279, in cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.oBugReport.fPostProcess(oCdbWrapper);
  File "C:\Users\s\Desktop\BugID\modules\cBugId\cBugReport.py", line 281
, in fPostProcess
    sDesiredDumpFileName = "%s @ %s.dmp" % (oBugId.oBugReport.sId, oBugId.oBugRe
port.sBugLocation);
NameError: global name 'oBugId' is not defined

+ BugId run into an internal error:
  NameError("global name 'oBugId' is not defined",)
```

**Comment by SkyLined** [comment]
Thanks again for reporting these! I've fixed the issue: that some old code using a reference (`oBugId.oBugReport`) to the report that had been updated (to `oBugReport`), which was causing the error. The fix was very simple, please try the new version and reopen the case if you are still seeing issues.

I apologize for the inconvenience.
