### ISSUE TITLE
AssertionError: unexpected value result

### ISSUE THREAD

**Issue by dmitrikaslov** [SkyLined/BugId#24]
Hi SkyLined

Found this bug today on the new version:
```
 * T+164.4 Exception code 0xC0000005 (Access violation) was detected and is being analyzed...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\s\Desktop\BugId-master\modules\cBugId\cCdbWrapper.py", line 214, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "C:\Users\s\Desktop\BugId-master\modules\cBugId\cCdbWrapper.py", line 208, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\Users\s\Desktop\BugId-master\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 276, in cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.oBugReport = cBugReport.foCreateForException(oCdbWrapper, uExceptionCode, sExceptionDescription);
  File "C:\Users\s\Desktop\BugId-master\modules\cBugId\cBugReport.py", line 86, in foCreateForException
    oStack = cStack.foCreate(oCdbWrapper, uStackFramesCount);
  File "C:\Users\s\Desktop\BugId-master\modules\cBugId\cStack.py", line 99, in foCreate
    uInstructionPointer = oCdbWrapper.fuGetValue("@$ip");
  File "C:\Users\s\Desktop\BugId-master\modules\cBugId\cCdbWrapper.py", line 350, in fuGetValue
    "Unexpected value result:\r\n%s" % "\r\n".join(asValueResult);
AssertionError: Unexpected value result:
Unable to read dynamic function table entry at 00000280`877ea0d0
00007ff87995501f

+ BugId run into an internal error:
  AssertionError('Unexpected value result:\r\nUnable to read dynamic function table entry at 00000280`877ea0d0\r\n00007ff87995501f',)

BugId version 2016.10.04.2152, cBugId version 2016.10.04.2123
```

**Comment by SkyLined** [comment]
Thanks, fix should be live in a few minutes

**Comment by SkyLined** [comment]
This fixed the issue:
https://github.com/SkyLined/cBugId/commit/dd496d9d0e1bb768f206ce73518f9b7d8c5d7820
If you could reproduce the issue, can you check if it no longer causes an internal error in the latest version?
