### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by hacksysteam** [SkyLined/BugId#29]
Unexpected Crash

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\BugId\modules\cBugId\cCdbWrapper.py", line 224, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "C:\BugId\modules\cBugId\cCdbWrapper.py", line 218, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\BugId\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 106, in
 cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.fApplicationRunningCallback and oCdbWrapper.fApplicationRunningC
allback();
  File "C:\BugId\BugId.py", line 244, in fApplicationRunningHandler
    oBugId.fSetCheckForExcessiveCPUUsageTimeout(dxConfig["nExcessiveCPUUsageChec
kInitialTimeout"]);
AttributeError: 'NoneType' object has no attribute 'fSetCheckForExcessiveCPUUsag
eTimeout'

+ BugId run into an internal error:
  AttributeError("'NoneType' object has no attribute 'fSetCheckForExcessiveCPUUs
ageTimeout'",)

BugId version 2016.11.08.1614, cBugId version 2016.11.04.1335
```

**Comment by hacksysteam** [comment]
Seems working in the new version. Closing the issue and will re-open if the issue persists.
