### ISSUE TITLE
AssertionError: The value 0x00000102 is defined with description The given Timeout interval expired. and The wait operation timed out.

### ISSUE THREAD

**Issue by kkuehl** [SkyLined/BugId#59]
C:\Users\kkuehl\Downloads\BugId>python ./BugId.py "C:\Program Files\Internet Explorer\iexplore.exe"  -- http://www.google.com
Traceback (most recent call last):
  File "./BugId.py", line 47, in <module>
    __import__(sModuleName, globals(), locals(), [], -1);
  File "C:\Users\kkuehl\Downloads\cBugId\__init__.py", line 1, in <module>
    from cBugId import cBugId;
  File "C:\Users\kkuehl\Downloads\cBugId\cBugId.py", line 50, in <module>
    from cCdbWrapper import cCdbWrapper;
  File "C:\Users\kkuehl\Downloads\cBugId\cCdbWrapper.py", line 12, in <module>
    from cCdbWrapper_fCdbStdInOutThread import cCdbWrapper_fCdbStdInOutThread;
  File "C:\Users\kkuehl\Downloads\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 2, in <module>
    from cBugReport import cBugReport;
  File "C:\Users\kkuehl\Downloads\cBugId\cBugReport.py", line 10, in <module>
    from cBugReport_foAnalyzeException_STATUS_STOWED_EXCEPTION import cBugReport_foAnalyzeException_STATUS_STOWED_EXCEPTION;
  File "C:\Users\kkuehl\Downloads\cBugId\cBugReport_foAnalyzeException_STATUS_STOWED_EXCEPTION.py", line 2, in <module>
    from cStowedException import cStowedException;
  File "C:\Users\kkuehl\Downloads\cBugId\cStowedException.py", line 6, in <module>
    import mWindowsDefines;
  File "C:\Users\kkuehl\Downloads\cBugId\mWindowsDefines.py", line 9576, in <module>
    (oWindowsDefine.uValue, oExistingDefine.sDescription, oWindowsDefine.sDescription);
AssertionError: The value 0x00000102 is defined with description The given Timeout interval expired. and The wait operation timed out.

**Comment by kkuehl** [comment]
kkuehl@DESKTOP-26P6KM3 /cygdrive/c/Users/kkuehl/Downloads/cBugId
$ grep -n "The given Timeout interval" mWindowsDefines.py
32:  sDescription =    "The given Timeout interval expired.");

kkuehl@DESKTOP-26P6KM3 /cygdrive/c/Users/kkuehl/Downloads/cBugId
$ grep -n "The wait operation" mWindowsDefines.py
808:  sDescription =    "The wait operation timed out.");

**Comment by kkuehl** [comment]
Just commenting out one of the two conflicting values works.

**Comment by SkyLined** [comment]
Thanks for the report; you are right about the root cause. I already fixed this in my private build. This should be resolved when I commit the latest versions some time this week.
