### ISSUE TITLE
crash on latest version python 2.7 latest x64 x86

### ISSUE THREAD

**Issue by overloardz** [SkyLined/BugId#82]
tested on windows 10 x64 with both x64 and x86 python 2.7 latest

```
┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────
│ AssertionError('Unexpected list module output:  All Rights Reserved.\r\nstart    end        module name\r\n61350000 61410000   acro32    (export symbols)       C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\acro32.dll\r\n    Loaded symbol image file: C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\acro32.dll\r\n    Image path: C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\acro32.dll\r\n    Image name: acro32.dll\r\n    Timestamp:        Fri Oct 27 14:40:54 2017 (59F3A7E6)\r\n    CheckSum:         000C6E5E\r\n    ImageSize:        000C0000\r\n    File version:     1.2.2.39492\r\n    Product version:  1.2.2.39492\r\n    File flags:       0 (Mask 3F)\r\n    File OS:          40004 NT Win32\r\n    File type:        2.0 Dll\r\n    File date:        00000000.00000000\r\n    Translations:     0409.04e4\r\n    Information from resource tables:\r\n        CompanyName:      Adobe Systems Incorporated\r\n        ProductName:      acro32 2017/10/28-02:37:53\r\n        InternalName:     acro32\r\n        OriginalFilename: acro32.dll\r\n        ProductVersion:   \r\n        FileVersion:      1.2.2.39492\r\n        FileDescription:  Adobe Core Library\r\n        LegalCopyright:   \xa9 2009 Adobe Systems Incorporated.\r\n All Rights Reserved.\r\n        LegalTrademarks:  Adobe \xae',)
│
│  Stack:
│   0 fProcess_lmov_Output @ C:\BugiD\modules\cBugId\cModule.py/264
│      > "Unexpected list module output: %s\r\n%s" % (sLine, "\r\n".join(as_lmov_Output));
│   1 __foGetOrCreateFrom_lmov @ C:\BugiD\modules\cBugId\cModule.py/150
│      > oModule.fProcess_lmov_Output(as_lmov_Output);
│   2 foCreateForCdbId @ C:\BugiD\modules\cBugId\cModule.py/134
│      > return cModule.__foGetOrCreateFrom_lmov(oProcess, "m %s;" % sCdbId);
│   3 foGetOrCreateModuleForCdbId @ C:\BugiD\modules\cBugId\cProcess.py/69
│      > return cModule.foCreateForCdbId(oProcess, sCdbId);
│   4 ftoCallModuleAndFunctionFromCallInstructionForReturnAddress @ C:\BugiD\modules\cBugId\ftoCallModuleAndFunctionFromCallInstructionForReturnAddress.py/72
│      > oModule = oProcess.foGetOrCreateModuleForCdbId(sModuleCdbId);
│   5 foCreate @ C:\BugiD\modules\cBugId\cStack.py/212
│      > toCallModuleAndFunction = ftoCallModuleAndFunctionFromCallInstructionForReturnAddress(oProcess, uReturnAddress);
│   6 oStack @ C:\BugiD\modules\cBugId\cBugReport.py/92
│      > oBugReport.__oStack = cStack.foCreate(oBugReport.__oProcess, oBugReport.__oThread, oBugReport.uStackFramesCount);
│   7 fbApplyToBugReport @ C:\BugiD\modules\cBugId\BugTranslations\cBugTranslation.py/98
│      > if oBugReport.oStack.fbTopFramesMatchSymbols(asAdditionalIrrelevantStackFrameSymbols, \
│   8 fApplyBugTranslationsToBugReport @ C:\BugiD\modules\cBugId\BugTranslations\fApplyBugTranslationsToBugReport.py/53
│      > if oBugTranslation.fbApplyToBugReport(oBugReport):
│   9 foCreateForException @ C:\BugiD\modules\cBugId\cBugReport.py/123
│      > fApplyBugTranslationsToBugReport(oBugReport);
│  10 cCdbWrapper_fCdbStdInOutHelperThread @ C:\BugiD\modules\cBugId\cCdbWrapper_fCdbStdInOutHelperThread.py/408
│      > oException,
│  11 fCdbStdInOutHelperThread @ C:\BugiD\modules\cBugId\cCdbWrapper.py/369
│      > return cCdbWrapper_fCdbStdInOutHelperThread(oCdbWrapper);
│  12 __fRun @ C:\BugiD\modules\cBugId\cHelperThread.py/59
│      > oSelf.__fActivity(*oSelf.__axActivityArguments);
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


┌─ Version information ────────────────────────────────────────────────────────────────────────────────────────────────
│ ∙ BugId version: 2018-05-30 19:58 (in trial period).
log>helper thread terminated (Thread: Thread #4800 [cdb.exe stdin/out thread] <bound method cCdbWrapper.fCdbStdInOutHelperThread of <cBugId.cCdbWrapper.cCdbWrapper object at 0x00000000046B1240>>())
log>cdb stdin/out closed
log>Failed to read from cdb.exe stderr
log>helper thread terminated (Thread: Thread #644 [Application stdout thread for process 2432/0x980] <bound method cCdbWrapper.fApplicationStdOutOrErrHelperThread of <cBugId.cCdbWrapper.cCdbWrapper object at 0x00000000046B1240>>(<mWindowsAPI.cConsoleProcess.cConsoleProcess object at 0x00000000046B1A58>, <mWindowsAPI.cPipe.cPipe object at 0x00000000046B1CC0>))
log>helper thread terminated (Thread: Thread #1948 [Application stderr thread for process 2432/0x980] <bound method cCdbWrapper.fApplicationStdOutOrErrHelperThread of <cBugId.cCdbWrapper.cCdbWrapper object at 0x00000000046B1240>>(<mWindowsAPI.cConsoleProcess.cConsoleProcess object at 0x00000000046B1A58>, <mWindowsAPI.cPipe.cPipe object at 0x00000000046B1978>))
log>helper thread terminated (Thread: Thread #668 [cdb.exe stderr thread] <bound method cCdbWrapper.fCdbStdErrHelperThread of <cBugId.cCdbWrapper.cCdbWrapper object at 0x00000000046B1240>>())E
xception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\BugiD\modules\cBugId\cHelperThread.py", line 67, in __fRun
    if not oSelf.__oCdbWrapper.fbFireEvent("Internal exception", oException, oTraceBack):
  File "C:\BugiD\modules\cBugId\cCdbWrapper.py", line 403, in fbFireEvent
    fCallback(*axCallbackArguments);
  File "C:\BugiD\modules\cBugId\cBugId.py", line 196, in <lambda>
    lambda *axArguments: fCallback(oBugId, *axArguments),
  File "C:\BugiD\BugId.py", line 124, in fInternalExceptionCallback
    fPrintExceptionInformation(oException, oTraceBack);
  File "C:\BugiD\fPrintExceptionInformation.py", line 46, in fPrintExceptionInformation
    bShowInstallationFolders = False,
  File "C:\BugiD\fPrintVersionInformation.py", line 108, in fPrintVersionInformation
    fPrintProductDetails(oMainProductDetails, bIsMainProduct = True, bShowInstallationFolders = bShowInstallationFolders);
  File "C:\BugiD\fPrintVersionInformation.py", line 29, in fPrintProductDetails
    if oProductDetails.oLatestProductVersion:
  File "C:\BugiD\modules\mProductDetails\cProductDetails.py", line 133, in oLatestProductVersion
    return oSelf.oLatestProductDetailsFromRepository and oSelf.oLatestProductDetailsFromRepository.oProductVersion;
  File "C:\BugiD\modules\mProductDetails\cProductDetails.py", line 126, in oLatestProductDetailsFromRepository
    sProductDetailsJSONData = oSelf.oRepository.sLatestProductDetailsJSONData,
  File "C:\BugiD\modules\mProductDetails\cGitHubRepository.py", line 27, in sLatestProductDetailsJSONData
    cException = cGitHubRepository.cGitHubServerErrorException,
  File "C:\BugiD\modules\mProductDetails\fsGetHTTPResponseData.py", line 12, in fsGetHTTPResponseData
    oSSLContext = ssl.create_default_context();
AttributeError: 'module' object has no attribute 'create_default_context'
```
test for acrobat x64

seems like invalid character in product info of DLL can you push a fix seems not usable in current version.

**Comment by overloardz** [comment]
tested with Release 2018-05-30

**Comment by SkyLined** [comment]
Thank you for the report! This is issue #55, which I know how to fix but haven't had time to implement.
