### ISSUE TITLE
C++ Exception fails Win10 x64

### ISSUE THREAD

**Issue by bnagy** [SkyLined/BugId#9]
```
+ StaticBufferOverrun10 Write 20 =x86=> FailFast2:StackCookie
@ Exception in C++ =x86=> C++:cException: need more than 1 value to unpack
Exception in thread Thread-242:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\BugId\src\cCdbWrapper.py", line 98, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "C:\BugId\src\cCdbWrapper.py", line 92, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\BugId\src\cCdbWrapper_fCdbStdInOutThread.py", line 169, in cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.oErrorReport = cErrorReport.foCreate(oCdbWrapper, uExceptionCode, sExceptionDescription);
  File "C:\BugId\src\cErrorReport.py", line 115, in foCreate
    oErrorReport = foSpecialErrorReport(oErrorReport, oCdbWrapper);
  File "C:\BugId\src\cErrorReport_foSpecialErrorReport_CppException.py", line 55, in cErrorReport_foSpecialErrorReport_CppException
    sModuleCdbId, sExceptionClassName = sExceptionObjectSymbol.split("!", 1);
ValueError: need more than 1 value to unpack

* Tests failed.
```

**Comment by SkyLined** [comment]
In this case, apparently the symbol for the exception class is not available. This should not happen if you build the test yourself and have the right .pdb file... can you check if you have the right symbols for Tests.exe?

However, the BugId code should not throw an exception when the symbol for the C++ exception class is not available. I've updated the code to check for "!" before attempting to split it. If it's not found, it assumes there is no symbol. Can you test with the latest version?
